### ISSUE TITLE
Windows password hiding issue.

### ISSUE THREAD

**Issue by le0tan** [indocomsoft/fluminus_cli#3]
On Windows, when logging in, the password field would look like:
```bash
username: e0123456
password: [2KK
[hidden]
```
The `[2KK` should not be there. (It is not the password but some sort of hiding character being displayed I guess?)

**Comment by indocomsoft** [comment]
Oh man, yes. Overall the package is not really tested with Windows. If all you need is file downloading, I suggest using fluminurs instead: https://github.com/indocomsoft/fluminurs

**Comment by indocomsoft** [comment]
Closing after adding link to fluminurs in README
