### ISSUE TITLE
Unable to download files unless --verbose is added

### ISSUE THREAD

**Issue by ktaekwon000** [indocomsoft/fluminus_cli#50]
Hi, I noticed this weird bug where fluminus_cli is unable to download files unless --verbose is enabled.

```
xxxxxx:~/fluminus_cli$ mix fluminus
Hi (name)
You are taking:
(module list)
And teaching:

xxxxxx:~/fluminus_cli$ mix fluminus --download-to=/tmp/flu
Hi (name)
You are taking:
(module list)
And teaching:

Download to /tmp/flu
^C
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
a
xxxxxx:~/fluminus_cli$ mix fluminus --show-errors --download-to=/tmp/flu
Hi (name)
You are taking:
(module list)
And teaching:

Download to /tmp/flu

03:40:09.679 [error] %FunctionClauseError{args: nil, arity: 5, clauses: nil, function: :download_file_wrapper, kind: nil, module: FluminusCLI}

03:40:09.679 [error] %FunctionClauseError{args: nil, arity: 5, clauses: nil, function: :download_file_wrapper, kind: nil, module: FluminusCLI}

# (error repeats every millisecond or so)

^C
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
a
xxxxxx:~/fluminus_cli$ mix fluminus --verbose --show-errors --download-to=/tmp/flu
Hi (name)
You are taking:
(module list)
And teaching:

Download to /tmp/flu
Downloaded to /tmp/flu/(correct file)
xxxxxx:~/fluminus_cli$
```

Edit: Commented in the wrong place, sorry.

I'm on WSL, if that matters.

**Comment by ktaekwon000** [comment]
I just tested some stuff, this bug does not occur with code from commit https://github.com/indocomsoft/fluminus_cli/commit/0f12d7cba7ed704513ddcb8982fe7bddbc167d87 .

**Comment by indocomsoft** [comment]
I think this happened to another person too. Hmmm, are you saying `0f12d7cba7ed704513ddcb8982fe7bddbc167d87` is when it broke, or the last commit where things work?

**Comment by indocomsoft** [comment]
Also, do you have any unpublished modules on luminus?

**Comment by ktaekwon000** [comment]
0f12d7cba7ed704513ddcb8982fe7bddbc167d87 is the last commit where things work.

Regarding modules, I have one module that "has not been created or published yet" and one that "the module coordinator has extended your access to this module".

**Comment by indocomsoft** [comment]
Ah, I think I found out where I screwed up. Can you try the latest `master`? https://github.com/indocomsoft/fluminus_cli/commit/1254a7ca3e2927c05413ac7e0ab35407e0558549

**Comment by ktaekwon000** [comment]
Works great now!

Thanks a lot for your work on this 😄
